version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: 
      Name: Running Test
      command: 
      echo Running Test
      mkdir -p /tmp/test-result
      make test
      